{"id": "CVE-2021-28658", "package": "pkg:pypi/django@2.2.4", "purl": "pkg:pypi/django@2.2.4", "package_type": "pip", "package_usage": "N/A", "version": "2.2.4", "fix_version": "2.2.20", "severity": "MEDIUM", "cvss_score": "5.0", "short_description": "# Directory Traversal in Django\nIn Django 2.2 before 2.2.20, 3.0 before 3.0.14, and 3.1 before 3.1.8, MultiPartParser allowed directory traversal via uploaded files with suitably crafted file names. Built-in upload handlers were not affected by this vulnerability.\n            ", "related_urls": ["https://nvd.nist.gov/vuln/detail/CVE-2021-28658", "https://github.com/advisories/GHSA-xgxc-v2qg-chmh"]}
{"id": "CVE-2021-3281", "package": "pkg:pypi/django@2.2.4", "purl": "pkg:pypi/django@2.2.4", "package_type": "pip", "package_usage": "N/A", "version": "2.2.4", "fix_version": "2.2.18", "severity": "MEDIUM", "cvss_score": "5.0", "short_description": "# Improper Limitation of a Pathname to a Restricted Directory\nIn Django 2.2 before 2.2.18, 3.0 before 3.0.12, and 3.1 before 3.1.6, the django.utils.archive.extract method (used by \"startapp --template\" and \"startproject --template\") allows directory traversal via an archive with absolute paths or relative paths with dot segments.\n            ", "related_urls": ["https://nvd.nist.gov/vuln/detail/CVE-2021-3281", "https://github.com/advisories/GHSA-fvgf-6h6h-3322"]}
{"id": "CVE-2020-25626", "package": "pkg:pypi/djangorestframework@3.11.0", "purl": "pkg:pypi/djangorestframework@3.11.0", "package_type": "pip", "package_usage": "N/A", "version": "3.11.0", "fix_version": "3.11.2", "severity": "MEDIUM", "cvss_score": "5.0", "short_description": "# Cross-site Scripting (XSS) in Django REST Framework\nA flaw was found in Django REST Framework versions before 3.12.0 and before 3.11.2. When using the browseable API viewer, Django REST Framework fails to properly escape certain strings that can come from user input. This allows a user who can control those strings to inject malicious <script> tags, leading to a cross-site-scripting (XSS) vulnerability.\n            ", "related_urls": ["https://nvd.nist.gov/vuln/detail/CVE-2020-25626", "https://github.com/advisories/GHSA-fx83-3ph3-9j2q"]}
{"id": "CVE-2020-24583", "package": "pkg:pypi/django@2.2.4", "purl": "pkg:pypi/django@2.2.4", "package_type": "pip", "package_usage": "N/A", "version": "2.2.4", "fix_version": "2.2.16", "severity": "HIGH", "cvss_score": "7.5", "short_description": "# Incorrect Default Permissions\nAn issue was discovered in Django 2.2 before 2.2.16, 3.0 before 3.0.10, and 3.1 before 3.1.1 (when Python 3.7+ is used). FILE_UPLOAD_DIRECTORY_PERMISSIONS mode was not applied to intermediate-level directories created in the process of uploading files. It was also not applied to intermediate-level collected static directories when using the collectstatic management command.\n            ", "related_urls": ["https://nvd.nist.gov/vuln/detail/CVE-2020-24583", "https://github.com/advisories/GHSA-m6gj-h9gm-gw44"]}
{"id": "CVE-2020-24584", "package": "pkg:pypi/django@2.2.4", "purl": "pkg:pypi/django@2.2.4", "package_type": "pip", "package_usage": "N/A", "version": "2.2.4", "fix_version": "2.2.16", "severity": "HIGH", "cvss_score": "7.5", "short_description": "# Incorrect Default Permissions\nAn issue was discovered in Django 2.2 before 2.2.16, 3.0 before 3.0.10, and 3.1 before 3.1.1 (when Python 3.7+ is used). The intermediate-level directories of the filesystem cache had the system's standard umask rather than 0o077.\n            ", "related_urls": ["https://nvd.nist.gov/vuln/detail/CVE-2020-24584", "https://github.com/advisories/GHSA-fr28-569j-53c4"]}
{"id": "CVE-2021-23336", "package": "pkg:pypi/python@2.7.12", "purl": "pkg:pypi/python@2.7.12", "package_type": "python", "package_usage": "N/A", "version": "2.7.12", "fix_version": "3.6.13", "severity": "MEDIUM", "cvss_score": "5.9", "short_description": "The package python/cpython from 0 and before 3.6.13, from 3.7.0 and before 3.7.10, from 3.8.0 and before 3.8.8, from 3.9.0 and before 3.9.2 are vulnerable to Web Cache Poisoning via urllib.parse.parse_qsl and urllib.parse.parse_qs by using a vector called parameter cloaking. When the attacker can separate query parameters using a semicolon (;), they can cause a difference in the interpretation of the request between the proxy (running with default configuration) and the server. This can result in malicious requests being cached as completely safe ones, as the proxy would usually not see the semicolon as a separator, and therefore would not include it in a cache key of an unkeyed parameter.", "related_urls": ["https://snyk.io/vuln/SNYK-UPSTREAM-PYTHONCPYTHON-1074933", "https://github.com/python/cpython/pull/24297", "https://snyk.io/blog/cache-poisoning-in-popular-open-source-packages/", "http://www.openwall.com/lists/oss-security/2021/02/19/4", "https://lists.debian.org/debian-lts-announce/2021/02/msg00030.html", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HCQTCSP6SCVIYNIRUJC5X7YBVUHPLSC4/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NODWHDIFBQE5RU5PUWUVE47JOT5VCMJ2/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MNUN5SOMFL2BBKP6ZAICIIUPQKZDMGYO/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MP572OLHMS7MZO4KUPSCIMSZIA5IZZ62/", "https://lists.apache.org/thread.html/rf9fa47ab66495c78bb4120b0754dd9531ca2ff0430f6685ac9b07772@%3Cdev.mina.apache.org%3E", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FONHJIOZOFD7CD35KZL6SVBUTMBPGZGA/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KJXCMHLY7H3FIYLE4OKDYUILU2CCRUCZ/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/3YKKDLXL3UEZ3J426C2XTBS63AHE46SM/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/TFTELUMWZE3KV3JB2H5EE6VFRZFRD5MV/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/OAGSWNGZJ6HQ5ISA67SNMK3CJRKICET7/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NJSCSN722JO2E2AGPWD4NTGVELVRPB4R/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HZTM7KLHFCE3LWSEVO2NAFLUHMGYMCRY/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/3EPYWWFDV22CJ5AOH5VCE72DOASZZ255/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IHQDU7NXA7EWAE4W7VO6MURVJIULEPPR/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/LVNH6Z24IG3E67ZCQGGJ46FZB4XFLQNZ/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/W2LSKBEFI5SYEY5FM6ICZVZM5WRQUCS4/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/46N6A52EGSXHJYCZWVMBJJIH4NWIV2B5/", "https://security.netapp.com/advisory/ntap-20210326-0004/", "https://lists.debian.org/debian-lts-announce/2021/04/msg00005.html", "https://lists.debian.org/debian-lts-announce/2021/04/msg00015.html", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/N6VXJZSZ6N64AILJX4CTMACYGQGHHD5C/", "https://security.gentoo.org/glsa/202104-04", "https://lists.apache.org/thread.html/ra8ce70088ba291f358e077cafdb14d174b7a1ce9a9d86d1b332d6367@%3Cusers.airflow.apache.org%3E", "http://www.openwall.com/lists/oss-security/2021/05/01/2", "https://lists.apache.org/thread.html/rc005f4de9d9b0ba943ceb8ff5a21a5c6ff8a9df52632476698d99432@%3Cannounce.apache.org%3E"]}
{"id": "CVE-2021-23364", "package": "pkg:npm/browserslist@4.10.0", "purl": "pkg:npm/browserslist@4.10.0", "package_type": "npm", "package_usage": "N/A", "version": "4.10.0", "fix_version": "4.16.5", "severity": "MEDIUM", "cvss_score": "5.3", "short_description": "The package browserslist from 4.0.0 and before 4.16.5 are vulnerable to Regular Expression Denial of Service (ReDoS) during parsing of queries.", "related_urls": ["https://snyk.io/vuln/SNYK-JAVA-ORGWEBJARSNPM-1277182", "https://github.com/browserslist/browserslist/commit/c091916910dfe0b5fd61caad96083c6709b02d98", "https://github.com/browserslist/browserslist/pull/593", "https://github.com/browserslist/browserslist/blob/e82f32d1d4100d6bc79ea0b6b6a2d281a561e33c/index.js%23L472-L474", "https://snyk.io/vuln/SNYK-JS-BROWSERSLIST-1090194"]}
{"id": "CVE-2021-27290", "package": "pkg:npm/ssri@6.0.2", "purl": "pkg:npm/ssri@6.0.2", "package_type": "npm", "package_usage": "N/A", "version": "6.0.2", "fix_version": "8.0.1", "severity": "HIGH", "cvss_score": "7.5", "short_description": "ssri 5.2.2-8.0.0, fixed in 8.0.1, processes SRIs using a regular expression which is vulnerable to a denial of service. Malicious SRIs could take an extremely long time to process, leading to denial of service. This issue only affects consumers using the strict option.", "related_urls": ["https://doyensec.com/resources/Doyensec_Advisory_ssri_redos.pdf", "https://npmjs.com", "https://github.com/yetingli/SaveResults/blob/main/pdf/ssri-redos.pdf"]}
{"id": "CVE-2021-31542", "package": "pkg:pypi/django@2.2.4", "purl": "pkg:pypi/django@2.2.4", "package_type": "djangoproject", "package_usage": "N/A", "version": "2.2.4", "fix_version": "2.2.21", "severity": "HIGH", "cvss_score": "7.5", "short_description": "In Django 2.2 before 2.2.21, 3.1 before 3.1.9, and 3.2 before 3.2.1, MultiPartParser, UploadedFile, and FieldFile allowed directory traversal via uploaded files with suitably crafted file names.", "related_urls": ["https://www.djangoproject.com/weblog/2021/may/04/security-releases/", "https://docs.djangoproject.com/en/3.2/releases/security/", "http://www.openwall.com/lists/oss-security/2021/05/04/3", "https://groups.google.com/forum/#!forum/django-announce", "https://lists.debian.org/debian-lts-announce/2021/05/msg00005.html", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZVKYPHR3TKR2ESWXBPOJEKRO2OSJRZUE/"]}
{"id": "CVE-2021-32052", "package": "pkg:pypi/django@2.2.4", "purl": "pkg:pypi/django@2.2.4", "package_type": "djangoproject", "package_usage": "N/A", "version": "2.2.4", "fix_version": "2.2.22", "severity": "MEDIUM", "cvss_score": "6.1", "short_description": "In Django 2.2 before 2.2.22, 3.1 before 3.1.10, and 3.2 before 3.2.2 (with Python 3.9.5+), URLValidator does not prohibit newlines and tabs (unless the URLField form field is used). If an application uses values with newlines in an HTTP response, header injection can occur. Django itself is unaffected because HttpResponse prohibits newlines in HTTP headers.", "related_urls": ["https://docs.djangoproject.com/en/3.2/releases/security/", "http://www.openwall.com/lists/oss-security/2021/05/06/1", "https://groups.google.com/forum/#!forum/django-announce", "https://www.djangoproject.com/weblog/2021/may/06/security-releases/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZVKYPHR3TKR2ESWXBPOJEKRO2OSJRZUE/"]}
{"id": "CVE-2020-13254", "package": "pkg:pypi/django@2.2.4", "purl": "pkg:pypi/django@2.2.4", "package_type": "djangoproject", "package_usage": "N/A", "version": "2.2.4", "fix_version": "2.2.13", "severity": "MEDIUM", "cvss_score": "5.9", "short_description": "An issue was discovered in Django 2.2 before 2.2.13 and 3.0 before 3.0.7. In cases where a memcached backend does not perform key validation, passing malformed cache keys could result in a key collision, and potential data leakage.", "related_urls": ["https://www.djangoproject.com/weblog/2020/jun/03/security-releases/", "https://docs.djangoproject.com/en/3.0/releases/security/", "https://groups.google.com/d/msg/django-announce/pPEmb2ot4Fo/X-SMalYSBAAJ", "https://usn.ubuntu.com/4381-1/", "https://usn.ubuntu.com/4381-2/", "https://security.netapp.com/advisory/ntap-20200611-0002/", "https://lists.debian.org/debian-lts-announce/2020/06/msg00016.html", "https://www.debian.org/security/2020/dsa-4705", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4A2AP4T7RKPBCLTI2NNQG3T6MINDUUMZ/", "https://www.oracle.com/security-alerts/cpujan2021.html"]}
{"id": "CVE-2020-13596", "package": "pkg:pypi/django@2.2.4", "purl": "pkg:pypi/django@2.2.4", "package_type": "djangoproject", "package_usage": "N/A", "version": "2.2.4", "fix_version": "2.2.13", "severity": "MEDIUM", "cvss_score": "6.1", "short_description": "An issue was discovered in Django 2.2 before 2.2.13 and 3.0 before 3.0.7. Query parameters generated by the Django admin ForeignKeyRawIdWidget were not properly URL encoded, leading to a possibility of an XSS attack.", "related_urls": ["https://www.djangoproject.com/weblog/2020/jun/03/security-releases/", "https://groups.google.com/forum/#!msg/django-announce/pPEmb2ot4Fo/X-SMalYSBAAJ", "https://docs.djangoproject.com/en/3.0/releases/security/", "https://usn.ubuntu.com/4381-1/", "https://usn.ubuntu.com/4381-2/", "https://security.netapp.com/advisory/ntap-20200611-0002/", "https://www.debian.org/security/2020/dsa-4705", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4A2AP4T7RKPBCLTI2NNQG3T6MINDUUMZ/", "https://www.oracle.com/security-alerts/cpujan2021.html"]}
{"id": "CVE-2020-15133", "package": "pkg:npm/faye-websocket@0.11.4", "purl": "pkg:npm/faye-websocket@0.11.4", "package_type": "faye-websocket_project", "package_usage": "N/A", "version": "0.11.4", "fix_version": "0.11.0", "severity": "HIGH", "cvss_score": "8.7", "short_description": "In faye-websocket before version 0.11.0, there is a lack of certification validation in TLS handshakes. The `Faye::WebSocket::Client` class uses the `EM::Connection#start_tls` method in EventMachine to implement the TLS handshake whenever a `wss:` URL is used for the connection. This method does not implement certificate verification by default, meaning that it does not check that the server presents a valid and trusted TLS certificate for the expected hostname. That means that any `wss:` connection made using this library is vulnerable to a man-in-the-middle attack, since it does not confirm the identity of the server it is connected to. For further background information on this issue, please see the referenced GitHub Advisory. Upgrading `faye-websocket` to v0.11.0 is recommended.", "related_urls": ["https://blog.jcoglan.com/2020/07/31/missing-tls-verification-in-faye/", "https://github.com/faye/faye-websocket-ruby/security/advisories/GHSA-2v5c-755p-p4gv"]}
{"id": "CVE-2020-28477", "package": "pkg:npm/immer@1.10.0", "purl": "pkg:npm/immer@1.10.0", "package_type": "npm", "package_usage": "N/A", "version": "1.10.0", "fix_version": "8.0.1", "severity": "HIGH", "cvss_score": "7.5", "short_description": "This affects all versions of package immer.", "related_urls": ["https://snyk.io/vuln/SNYK-JAVA-ORGWEBJARSNPM-1061986", "https://github.com/immerjs/immer/blob/master/src/plugins/patches.ts%23L213", "https://snyk.io/vuln/SNYK-JS-IMMER-1019369"]}
{"id": "CVE-2020-7471", "package": "pkg:pypi/django@2.2.4", "purl": "pkg:pypi/django@2.2.4", "package_type": "djangoproject", "package_usage": "N/A", "version": "2.2.4", "fix_version": "2.2.10", "severity": "CRITICAL", "cvss_score": "9.8", "short_description": "Django 1.11 before 1.11.28, 2.2 before 2.2.10, and 3.0 before 3.0.3 allows SQL Injection if untrusted data is used as a StringAgg delimiter (e.g., in Django applications that offer downloads of data as a series of rows with a user-specified column delimiter). By passing a suitably crafted delimiter to a contrib.postgres.aggregates.StringAgg instance, it was possible to break escaping and inject malicious SQL.", "related_urls": ["https://www.openwall.com/lists/oss-security/2020/02/03/1", "https://docs.djangoproject.com/en/3.0/releases/security/", "https://groups.google.com/forum/#!topic/django-announce/X45S86X5bZI", "https://www.djangoproject.com/weblog/2020/feb/03/security-releases/", "http://www.openwall.com/lists/oss-security/2020/02/03/1", "https://github.com/django/django/commit/eb31d845323618d688ad429479c6dda973056136", "https://usn.ubuntu.com/4264-1/", "https://seclists.org/bugtraq/2020/Feb/30", "https://www.debian.org/security/2020/dsa-4629", "https://security.netapp.com/advisory/ntap-20200221-0006/", "https://security.gentoo.org/glsa/202004-17", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4A2AP4T7RKPBCLTI2NNQG3T6MINDUUMZ/"]}
{"id": "CVE-2020-7663", "package": "pkg:npm/websocket-extensions@0.1.4", "purl": "pkg:npm/websocket-extensions@0.1.4", "package_type": "rubygems", "package_usage": "N/A", "version": "0.1.4", "fix_version": "0.1.5", "severity": "HIGH", "cvss_score": "7.5", "short_description": "websocket-extensions ruby module prior to 0.1.5 allows Denial of Service (DoS) via Regex Backtracking. The extension parser may take quadratic time when parsing a header containing an unclosed string parameter value whose content is a repeating two-byte sequence of a backslash and some other character. This could be abused by an attacker to conduct Regex Denial Of Service (ReDoS) on a single-threaded server by providing a malicious payload with the Sec-WebSocket-Extensions header.", "related_urls": ["https://blog.jcoglan.com/2020/06/02/redos-vulnerability-in-websocket-extensions", "https://github.com/faye/websocket-extensions-ruby/security/advisories/GHSA-g6wq-qcwm-j5g2", "https://github.com/faye/websocket-extensions-ruby/commit/aa156a439da681361ed6f53f1a8131892418838b", "https://snyk.io/vuln/SNYK-RUBY-WEBSOCKETEXTENSIONS-570830", "https://lists.debian.org/debian-lts-announce/2020/08/msg00031.html", "https://usn.ubuntu.com/4502-1/"]}
{"id": "CVE-2020-7788", "package": "pkg:npm/ini@1.3.8", "purl": "pkg:npm/ini@1.3.8", "package_type": "npm", "package_usage": "N/A", "version": "1.3.8", "fix_version": "1.3.6", "severity": "HIGH", "cvss_score": "7.3", "short_description": "This affects the package ini before 1.3.6. If an attacker submits a malicious INI file to an application that parses it with ini.parse, they will pollute the prototype on the application. This can be exploited further depending on the context.", "related_urls": ["https://snyk.io/vuln/SNYK-JS-INI-1048974", "https://github.com/npm/ini/commit/56d2805e07ccd94e2ba0984ac9240ff02d44b6f1", "https://lists.debian.org/debian-lts-announce/2020/12/msg00032.html"]}
{"id": "CVE-2020-7789", "package": "pkg:npm/node-notifier@5.4.5", "purl": "pkg:npm/node-notifier@5.4.5", "package_type": "npm", "package_usage": "N/A", "version": "5.4.5", "fix_version": "8.0.1", "severity": "MEDIUM", "cvss_score": "5.6", "short_description": "This affects the package node-notifier before 9.0.0. It allows an attacker to run arbitrary commands on Linux machines due to the options params not being sanitised when being passed an array.", "related_urls": ["https://snyk.io/vuln/SNYK-JAVA-ORGWEBJARSNPM-1050371", "https://snyk.io/vuln/SNYK-JS-NODENOTIFIER-1035794", "https://github.com/mikaelbr/node-notifier/blob/master/lib/utils.js%23L303"]}
{"id": "CVE-2020-8492", "package": "pkg:pypi/python@2.7.12", "purl": "pkg:pypi/python@2.7.12", "package_type": "python", "package_usage": "N/A", "version": "2.7.12", "fix_version": null, "severity": "MEDIUM", "cvss_score": "6.5", "short_description": "Python 2.7 through 2.7.17, 3.5 through 3.5.9, 3.6 through 3.6.10, 3.7 through 3.7.6, and 3.8 through 3.8.1 allows an HTTP server to conduct Regular Expression Denial of Service (ReDoS) attacks against a client because of urllib.request.AbstractBasicAuthHandler catastrophic backtracking.", "related_urls": ["https://github.com/python/cpython/pull/18284", "https://python-security.readthedocs.io/vuln/urllib-basic-auth-regex.html", "https://bugs.python.org/issue39503", "https://security.netapp.com/advisory/ntap-20200221-0001/", "http://lists.opensuse.org/opensuse-security-announce/2020-03/msg00003.html", "https://usn.ubuntu.com/4333-1/", "https://usn.ubuntu.com/4333-2/", "https://security.gentoo.org/glsa/202005-09", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/APGWEMYZIY5VHLCSZ3HD67PA5Z2UQFGH/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/7WOKDEXLYW5UQ4S7PA7E37IITOC7C56J/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/UESGYI5XDAHJBATEZN3MHNDUBDH47AS6/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/A5NSAX4SC3V64PGZUPH7PRDLSON34Q5A/", "https://lists.debian.org/debian-lts-announce/2020/07/msg00011.html"]}
{"id": "CVE-2020-9402", "package": "pkg:pypi/django@2.2.4", "purl": "pkg:pypi/django@2.2.4", "package_type": "djangoproject", "package_usage": "N/A", "version": "2.2.4", "fix_version": "2.2.11", "severity": "HIGH", "cvss_score": "8.8", "short_description": "Django 1.11 before 1.11.29, 2.2 before 2.2.11, and 3.0 before 3.0.4 allows SQL Injection if untrusted data is used as a tolerance parameter in GIS functions and aggregates on Oracle. By passing a suitably crafted tolerance to GIS functions and aggregates on Oracle, it was possible to break escaping and inject malicious SQL.", "related_urls": ["https://groups.google.com/forum/#!topic/django-announce/fLUh_pOaKrY", "https://www.djangoproject.com/weblog/2020/mar/04/security-releases/", "https://docs.djangoproject.com/en/3.0/releases/security/", "https://usn.ubuntu.com/4296-1/", "https://security.netapp.com/advisory/ntap-20200327-0004/", "https://security.gentoo.org/glsa/202004-17", "https://www.debian.org/security/2020/dsa-4705", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4A2AP4T7RKPBCLTI2NNQG3T6MINDUUMZ/"]}
{"id": "CVE-2019-16056", "package": "pkg:pypi/python@2.7.12", "purl": "pkg:pypi/python@2.7.12", "package_type": "python", "package_usage": "N/A", "version": "2.7.12", "fix_version": null, "severity": "HIGH", "cvss_score": "7.5", "short_description": "An issue was discovered in Python through 2.7.16, 3.x through 3.5.7, 3.6.x through 3.6.9, and 3.7.x through 3.7.4. The email module wrongly parses email addresses that contain multiple @ characters. An application that uses the email module and implements some kind of checks on the From/To headers of a message could be tricked into accepting an email address that should be denied. An attack may be the same as in CVE-2019-11340; however, this CVE applies to Python more generally.", "related_urls": ["https://bugs.python.org/issue34155", "https://github.com/python/cpython/commit/8cb65d1381b027f0b09ee36bfed7f35bb4dec9a9", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/K4KZEFP6E4YPYB52AF4WXCUDSGQOTF37/", "https://lists.debian.org/debian-lts-announce/2019/09/msg00019.html", "https://lists.debian.org/debian-lts-announce/2019/09/msg00018.html", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NF3DRDGMVIRYNZMSLJIHNW47HOUQYXVG/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ER6LONC2B2WYIO56GBQUDU6QTWZDPUNQ/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/E2HP37NUVLQSBW3J735A2DQDOZ4ZGBLY/", "https://security.netapp.com/advisory/ntap-20190926-0005/", "https://usn.ubuntu.com/4151-1/", "https://usn.ubuntu.com/4151-2/", "http://lists.opensuse.org/opensuse-security-announce/2019-10/msg00062.html", "http://lists.opensuse.org/opensuse-security-announce/2019-10/msg00063.html", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QP46PQSUKYPGWTADQ67NOV3BUN6JM34Z/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QASRD4E2G65GGEHYKVHYCXB2XWAGTNL4/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/SDQQ56P7ZZR64XV5DUVWNSNXKKEXUG2J/", "http://lists.opensuse.org/opensuse-security-announce/2019-11/msg00012.html", "https://access.redhat.com/errata/RHSA-2019:3725", "http://lists.opensuse.org/opensuse-security-announce/2019-11/msg00021.html", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/K7HNVIFMETMFWWWUNTB72KYJYXCZOS5V/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/M34WOYCDKTDE5KLUACE2YIEH7D37KHRX/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZBTGPBUABGXZ7WH7677OEM3NSP6ZEA76/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JCPGLTTOBB3QEARDX4JOYURP6ELNNA2V/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/COATURTCY7G67AYI6UDV5B2JZTBCKIDX/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4X3HW5JRZ7GCPSR7UHJOLD7AWLTQCDVR/", "https://access.redhat.com/errata/RHSA-2019:3948", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/BEARDOTXCYPYELKBD2KWZ27GSPXDI3GQ/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/OYGESQSGIHDCIGOBVF7VXCMIE6YDWRYB/", "http://lists.opensuse.org/opensuse-security-announce/2020-01/msg00040.html", "https://www.oracle.com/security-alerts/cpuapr2020.html", "https://www.oracle.com/security-alerts/cpujul2020.html", "https://lists.debian.org/debian-lts-announce/2020/07/msg00011.html", "https://lists.apache.org/thread.html/r1b103833cb5bc8466e24ff0ecc5e75b45a705334ab6a444e64e840a0@%3Cissues.bookkeeper.apache.org%3E", "https://lists.debian.org/debian-lts-announce/2020/08/msg00034.html"]}
{"id": "CVE-2019-16935", "package": "pkg:pypi/python@2.7.12", "purl": "pkg:pypi/python@2.7.12", "package_type": "python", "package_usage": "N/A", "version": "2.7.12", "fix_version": null, "severity": "MEDIUM", "cvss_score": "6.1", "short_description": "The documentation XML-RPC server in Python through 2.7.16, 3.x through 3.6.9, and 3.7.x through 3.7.4 has XSS via the server_title field. This occurs in Lib/DocXMLRPCServer.py in Python 2.x, and in Lib/xmlrpc/server.py in Python 3.x. If set_server_title is called with untrusted input, arbitrary JavaScript can be delivered to clients that visit the http URL for this server.", "related_urls": ["https://bugs.python.org/issue38243", "https://github.com/python/cpython/blob/e007860b8b3609ce0bc62b1780efaa06241520bd/Lib/DocXMLRPCServer.py#L213", "https://github.com/python/cpython/blob/35c0809158be7feae4c4f877a08b93baea2d8291/Lib/xmlrpc/server.py#L897", "https://github.com/python/cpython/pull/16373", "https://usn.ubuntu.com/4151-1/", "https://usn.ubuntu.com/4151-2/", "https://security.netapp.com/advisory/ntap-20191017-0004/", "http://lists.opensuse.org/opensuse-security-announce/2019-10/msg00062.html", "http://lists.opensuse.org/opensuse-security-announce/2019-10/msg00063.html", "http://lists.opensuse.org/opensuse-security-announce/2019-11/msg00012.html", "http://lists.opensuse.org/opensuse-security-announce/2019-11/msg00021.html", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/K7HNVIFMETMFWWWUNTB72KYJYXCZOS5V/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/M34WOYCDKTDE5KLUACE2YIEH7D37KHRX/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZBTGPBUABGXZ7WH7677OEM3NSP6ZEA76/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JCPGLTTOBB3QEARDX4JOYURP6ELNNA2V/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/COATURTCY7G67AYI6UDV5B2JZTBCKIDX/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4X3HW5JRZ7GCPSR7UHJOLD7AWLTQCDVR/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/BEARDOTXCYPYELKBD2KWZ27GSPXDI3GQ/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/OYGESQSGIHDCIGOBVF7VXCMIE6YDWRYB/", "http://lists.opensuse.org/opensuse-security-announce/2020-01/msg00040.html", "https://www.oracle.com/security-alerts/cpujul2020.html", "https://lists.debian.org/debian-lts-announce/2020/07/msg00011.html", "https://lists.debian.org/debian-lts-announce/2021/04/msg00015.html"]}
{"id": "CVE-2019-18348", "package": "pkg:pypi/python@2.7.12", "purl": "pkg:pypi/python@2.7.12", "package_type": "python", "package_usage": "N/A", "version": "2.7.12", "fix_version": null, "severity": "MEDIUM", "cvss_score": "6.1", "short_description": "An issue was discovered in urllib2 in Python 2.x through 2.7.17 and urllib in Python 3.x through 3.8.0. CRLF injection is possible if the attacker controls a url parameter, as demonstrated by the first argument to urllib.request.urlopen with \\r\\n (specifically in the host component of a URL) followed by an HTTP header. This is similar to the CVE-2019-9740 query string issue and the CVE-2019-9947 path string issue. (This is not exploitable when glibc has CVE-2016-10739 fixed.). This is fixed in: v2.7.18, v2.7.18rc1; v3.5.10, v3.5.10rc1; v3.6.11, v3.6.11rc1, v3.6.12; v3.7.8, v3.7.8rc1, v3.7.9; v3.8.3, v3.8.3rc1, v3.8.4, v3.8.4rc1, v3.8.5, v3.8.6, v3.8.6rc1.", "related_urls": ["https://bugs.python.org/issue30458#msg347282", "https://bugzilla.redhat.com/show_bug.cgi?id=1727276", "https://security.netapp.com/advisory/ntap-20191107-0004/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/M34WOYCDKTDE5KLUACE2YIEH7D37KHRX/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JCPGLTTOBB3QEARDX4JOYURP6ELNNA2V/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4X3HW5JRZ7GCPSR7UHJOLD7AWLTQCDVR/", "https://usn.ubuntu.com/4333-1/", "https://usn.ubuntu.com/4333-2/", "http://lists.opensuse.org/opensuse-security-announce/2020-05/msg00041.html", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/UESGYI5XDAHJBATEZN3MHNDUBDH47AS6/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/A5NSAX4SC3V64PGZUPH7PRDLSON34Q5A/", "https://lists.debian.org/debian-lts-announce/2020/07/msg00011.html", "https://www.oracle.com/security-alerts/cpuoct2020.html"]}
{"id": "CVE-2019-19118", "package": "pkg:pypi/django@2.2.4", "purl": "pkg:pypi/django@2.2.4", "package_type": "djangoproject", "package_usage": "N/A", "version": "2.2.4", "fix_version": "2.2.8", "severity": "MEDIUM", "cvss_score": "6.5", "short_description": "Django 2.1 before 2.1.15 and 2.2 before 2.2.8 allows unintended model editing. A Django model admin displaying inline related models, where the user has view-only permissions to a parent model but edit permissions to the inline model, would be presented with an editing UI, allowing POST requests, for updating the inline model. Directly editing the view-only parent model was not possible, but the parent model's save() method was called, triggering potential side effects, and causing pre and post-save signal handlers to be invoked. (To resolve this, the Django admin is adjusted to require edit permissions on the parent model in order for inline models to be editable.)", "related_urls": ["http://www.openwall.com/lists/oss-security/2019/12/02/1", "https://groups.google.com/forum/#!topic/django-announce/GjGqDvtNmWQ", "https://www.djangoproject.com/weblog/2019/dec/02/security-releases/", "https://docs.djangoproject.com/en/dev/releases/security/", "https://security.netapp.com/advisory/ntap-20191217-0003/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/6R4HD22PVEVQ45H2JA2NXH443AYJOPL5/", "https://security.gentoo.org/glsa/202004-17"]}
{"id": "CVE-2019-19844", "package": "pkg:pypi/django@2.2.4", "purl": "pkg:pypi/django@2.2.4", "package_type": "djangoproject", "package_usage": "N/A", "version": "2.2.4", "fix_version": "2.2.9", "severity": "CRITICAL", "cvss_score": "9.8", "short_description": "Django before 1.11.27, 2.x before 2.2.9, and 3.x before 3.0.1 allows account takeover. A suitably crafted email address (that is equal to an existing user's email address after case transformation of Unicode characters) would allow an attacker to be sent a password reset token for the matched user account. (One mitigation in the new releases is to send password reset tokens only to the registered user email address.)", "related_urls": ["https://groups.google.com/forum/#!topic/django-announce/3oaB2rVH3a0", "https://www.djangoproject.com/weblog/2019/dec/18/security-releases/", "https://docs.djangoproject.com/en/dev/releases/security/", "https://usn.ubuntu.com/4224-1/", "https://www.debian.org/security/2020/dsa-4598", "https://seclists.org/bugtraq/2020/Jan/9", "http://packetstormsecurity.com/files/155872/Django-Account-Hijack.html", "https://security.netapp.com/advisory/ntap-20200110-0003/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HCM2DPUI7TOZWN4A6JFQFUVQ2XGE7GUD/", "https://security.gentoo.org/glsa/202004-17"]}
{"id": "CVE-2019-20907", "package": "pkg:pypi/python@2.7.12", "purl": "pkg:pypi/python@2.7.12", "package_type": "python", "package_usage": "N/A", "version": "2.7.12", "fix_version": "3.7.9", "severity": "HIGH", "cvss_score": "7.5", "short_description": "In Lib/tarfile.py in Python through 3.8.3, an attacker is able to craft a TAR archive leading to an infinite loop when opened by tarfile.open, because _proc_pax lacks header validation.", "related_urls": ["https://bugs.python.org/issue39017", "https://github.com/python/cpython/pull/21454", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/VT4AF72TJ2XNIKCR4WEBR7URBJJ4YZRD/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/CAXHCY4V3LPAAJOBCJ26ISZ4NUXQXTUZ/", "https://usn.ubuntu.com/4428-1/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YSL3XWVDMSMKO23HR74AJQ6VEM3C2NTS/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/LE4O3PNDNNOMSKHNUKZKD3NGHIFUFDPX/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/TOGKLGTXZLHQQFBVCAPSUDA6DOOJFNRY/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/V3TALOUBYU2MQD4BPLRTDQUMBKGCAXUA/", "https://security.netapp.com/advisory/ntap-20200731-0002/", "https://security.gentoo.org/glsa/202008-01", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YILCHHTNLH4GG4GSQBX2MZRKZBXOLCKE/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PDKKRXLNVXRF6VGERZSR3OMQR5D5QI6I/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NTBKKOLFFNHG6CM4ACDX4APHSD5ZX5N4/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/CNHPQGSP2YM3JAUD2VAMPXTIUQTZ2M2U/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/V53P2YOLEQH4J7S5QHXMKMZYFTVVMTMO/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/CTUNTBJ3POHONQOTLEZC46POCIYYTAKZ/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/36XI3EEQNMHGOZEI63Y7UV6XZRELYEAU/", "https://lists.debian.org/debian-lts-announce/2020/08/msg00034.html", "http://lists.opensuse.org/opensuse-security-announce/2020-08/msg00051.html", "http://lists.opensuse.org/opensuse-security-announce/2020-08/msg00052.html", "http://lists.opensuse.org/opensuse-security-announce/2020-08/msg00053.html", "http://lists.opensuse.org/opensuse-security-announce/2020-08/msg00056.html", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/OXI72HIHMXCQFWTULUXDG7VDA2BCYL4Y/", "https://lists.debian.org/debian-lts-announce/2020/11/msg00032.html", "https://www.oracle.com/security-alerts/cpujan2021.html"]}
{"id": "CVE-2019-9636", "package": "pkg:pypi/python@2.7.12", "purl": "pkg:pypi/python@2.7.12", "package_type": "python", "package_usage": "N/A", "version": "2.7.12", "fix_version": null, "severity": "CRITICAL", "cvss_score": "9.8", "short_description": "Python 2.7.x through 2.7.16 and 3.x through 3.7.2 is affected by: Improper Handling of Unicode Encoding (with an incorrect netloc) during NFKC normalization. The impact is: Information disclosure (credentials, cookies, etc. that are cached against a given hostname). The components are: urllib.parse.urlsplit, urllib.parse.urlparse. The attack vector is: A specially crafted URL could be incorrectly parsed to locate cookies or authentication data and send that information to a different host than when parsed correctly. This is fixed in: v2.7.17, v2.7.17rc1, v2.7.18, v2.7.18rc1; v3.5.10, v3.5.10rc1, v3.5.7, v3.5.8, v3.5.8rc1, v3.5.8rc2, v3.5.9; v3.6.10, v3.6.10rc1, v3.6.11, v3.6.11rc1, v3.6.12, v3.6.9, v3.6.9rc1; v3.7.3, v3.7.3rc1, v3.7.4, v3.7.4rc1, v3.7.4rc2, v3.7.5, v3.7.5rc1, v3.7.6, v3.7.6rc1, v3.7.7, v3.7.7rc1, v3.7.8, v3.7.8rc1, v3.7.9.", "related_urls": ["https://python-security.readthedocs.io/vuln/urlsplit-nfkc-normalization.html", "https://github.com/python/cpython/pull/12201", "https://bugs.python.org/issue36216", "http://www.securityfocus.com/bid/107400", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/L25RTMKCF62DLC2XVSNXGX7C7HXISLVM/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JSKPGPZQNTAULHW4UH63KGOOUIDE4RRB/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/D3LXPABKVLFYUHRYJPM3CSS5MS6FXKS7/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/AEZ5IQT7OF7Q2NCGIVABOWYGKO7YU3NJ/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ICBEGRHIPHWPG2VGYS6R4EVKVUUF4AQW/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/TR6GCO3WTV4D5L23WTCBF275VE6BVNI3/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/CFBAAGM27H73OLYBUA2IAZFSUN6KGLME/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/46PVWY5LFP4BRPG3BVQ5QEEFYBVEXHCK/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IFAXBEY2TGOBDRKTR556JBXBVFSAKD6I/", "https://access.redhat.com/errata/RHSA-2019:0710", "https://access.redhat.com/errata/RHSA-2019:0765", "https://access.redhat.com/errata/RHSA-2019:0806", "http://lists.opensuse.org/opensuse-security-announce/2019-04/msg00092.html", "http://lists.opensuse.org/opensuse-security-announce/2019-04/msg00097.html", "https://access.redhat.com/errata/RHSA-2019:0902", "https://access.redhat.com/errata/RHSA-2019:0997", "https://access.redhat.com/errata/RHSA-2019:0981", "https://access.redhat.com/errata/RHBA-2019:0959", "http://lists.opensuse.org/opensuse-security-announce/2019-05/msg00024.html", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JXASHCDD4PQFKTMKQN4YOP5ZH366ABN4/", "https://security.netapp.com/advisory/ntap-20190517-0001/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JMWSKTNOHSUOT3L25QFJAVCFYZX46FYK/", "https://access.redhat.com/errata/RHSA-2019:1467", "http://lists.opensuse.org/opensuse-security-announce/2019-06/msg00050.html", "https://lists.debian.org/debian-lts-announce/2019/06/msg00022.html", "https://lists.debian.org/debian-lts-announce/2019/06/msg00023.html", "https://access.redhat.com/errata/RHBA-2019:0763", "https://access.redhat.com/errata/RHBA-2019:0764", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/44TS66GJMO5H3RLMVZEBGEFTB6O2LJJU/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/2ORNTF62QPLMJXIQ7KTZQ2776LMIXEKL/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KRYFIMISZ47NTAU3XWZUOFB7CYL62KES/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HQEQLXLOCR3SNM3AA5RRYJFQ5AZBYJ4L/", "http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00042.html", "https://usn.ubuntu.com/4127-2/", "https://usn.ubuntu.com/4127-1/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ER6LONC2B2WYIO56GBQUDU6QTWZDPUNQ/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/E2HP37NUVLQSBW3J735A2DQDOZ4ZGBLY/", "https://access.redhat.com/errata/RHSA-2019:2980", "https://access.redhat.com/errata/RHSA-2019:3170", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/M34WOYCDKTDE5KLUACE2YIEH7D37KHRX/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JCPGLTTOBB3QEARDX4JOYURP6ELNNA2V/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4X3HW5JRZ7GCPSR7UHJOLD7AWLTQCDVR/", "https://www.oracle.com/security-alerts/cpujan2020.html", "http://lists.opensuse.org/opensuse-security-announce/2020-01/msg00040.html", "https://security.gentoo.org/glsa/202003-26", "https://lists.debian.org/debian-lts-announce/2020/07/msg00011.html", "https://lists.debian.org/debian-lts-announce/2020/08/msg00034.html"]}
{"id": "CVE-2019-9674", "package": "pkg:pypi/python@2.7.12", "purl": "pkg:pypi/python@2.7.12", "package_type": "python", "package_usage": "N/A", "version": "2.7.12", "fix_version": null, "severity": "HIGH", "cvss_score": "7.5", "short_description": "Lib/zipfile.py in Python through 3.7.2 allows remote attackers to cause a denial of service (resource consumption) via a ZIP bomb.", "related_urls": ["https://github.com/python/cpython/blob/master/Lib/zipfile.py", "https://bugs.python.org/issue36462", "https://www.python.org/news/security/", "https://bugs.python.org/issue36260", "https://python-security.readthedocs.io/security.html#archives-and-zip-bomb", "https://security.netapp.com/advisory/ntap-20200221-0003/", "http://lists.opensuse.org/opensuse-security-announce/2020-03/msg00003.html", "http://lists.opensuse.org/opensuse-security-announce/2020-05/msg00041.html", "https://usn.ubuntu.com/4428-1/"]}
{"id": "CVE-2019-9740", "package": "pkg:pypi/python@2.7.12", "purl": "pkg:pypi/python@2.7.12", "package_type": "python", "package_usage": "N/A", "version": "2.7.12", "fix_version": null, "severity": "MEDIUM", "cvss_score": "6.1", "short_description": "An issue was discovered in urllib2 in Python 2.x through 2.7.16 and urllib in Python 3.x through 3.7.3. CRLF injection is possible if the attacker controls a url parameter, as demonstrated by the first argument to urllib.request.urlopen with \\r\\n (specifically in the query string after a ? character) followed by an HTTP header or a Redis command. This is fixed in: v2.7.17, v2.7.17rc1, v2.7.18, v2.7.18rc1; v3.5.10, v3.5.10rc1, v3.5.8, v3.5.8rc1, v3.5.8rc2, v3.5.9; v3.6.10, v3.6.10rc1, v3.6.11, v3.6.11rc1, v3.6.12, v3.6.9, v3.6.9rc1; v3.7.4, v3.7.4rc1, v3.7.4rc2, v3.7.5, v3.7.5rc1, v3.7.6, v3.7.6rc1, v3.7.7, v3.7.7rc1, v3.7.8, v3.7.8rc1, v3.7.9.", "related_urls": ["https://bugs.python.org/issue36276", "http://www.securityfocus.com/bid/107466", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JXASHCDD4PQFKTMKQN4YOP5ZH366ABN4/", "https://access.redhat.com/errata/RHSA-2019:1260", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JMWSKTNOHSUOT3L25QFJAVCFYZX46FYK/", "https://security.netapp.com/advisory/ntap-20190619-0005/", "https://lists.debian.org/debian-lts-announce/2019/06/msg00023.html", "https://lists.debian.org/debian-lts-announce/2019/06/msg00022.html", "https://lists.debian.org/debian-lts-announce/2019/06/msg00026.html", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/44TS66GJMO5H3RLMVZEBGEFTB6O2LJJU/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/2ORNTF62QPLMJXIQ7KTZQ2776LMIXEKL/", "https://access.redhat.com/errata/RHSA-2019:2030", "https://usn.ubuntu.com/4127-2/", "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00039.html", "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00041.html", "https://usn.ubuntu.com/4127-1/", "https://seclists.org/bugtraq/2019/Oct/29", "http://packetstormsecurity.com/files/154927/Slackware-Security-Advisory-python-Updates.html", "https://access.redhat.com/errata/RHSA-2019:3335", "https://access.redhat.com/errata/RHSA-2019:3520", "https://access.redhat.com/errata/RHSA-2019:3725", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/M34WOYCDKTDE5KLUACE2YIEH7D37KHRX/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JCPGLTTOBB3QEARDX4JOYURP6ELNNA2V/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4X3HW5JRZ7GCPSR7UHJOLD7AWLTQCDVR/", "https://security.gentoo.org/glsa/202003-26", "https://lists.debian.org/debian-lts-announce/2020/07/msg00011.html", "https://lists.debian.org/debian-lts-announce/2020/08/msg00034.html", "http://www.openwall.com/lists/oss-security/2021/02/04/2"]}
{"id": "CVE-2019-9947", "package": "pkg:pypi/python@2.7.12", "purl": "pkg:pypi/python@2.7.12", "package_type": "python", "package_usage": "N/A", "version": "2.7.12", "fix_version": null, "severity": "MEDIUM", "cvss_score": "6.1", "short_description": "An issue was discovered in urllib2 in Python 2.x through 2.7.16 and urllib in Python 3.x through 3.7.3. CRLF injection is possible if the attacker controls a url parameter, as demonstrated by the first argument to urllib.request.urlopen with \\r\\n (specifically in the path component of a URL that lacks a ? character) followed by an HTTP header or a Redis command. This is similar to the CVE-2019-9740 query string issue. This is fixed in: v2.7.17, v2.7.17rc1, v2.7.18, v2.7.18rc1; v3.5.10, v3.5.10rc1, v3.5.8, v3.5.8rc1, v3.5.8rc2, v3.5.9; v3.6.10, v3.6.10rc1, v3.6.11, v3.6.11rc1, v3.6.12, v3.6.9, v3.6.9rc1; v3.7.4, v3.7.4rc1, v3.7.4rc2, v3.7.5, v3.7.5rc1, v3.7.6, v3.7.6rc1, v3.7.7, v3.7.7rc1, v3.7.8, v3.7.8rc1, v3.7.9.", "related_urls": ["https://bugs.python.org/issue35906", "https://security.netapp.com/advisory/ntap-20190404-0004/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JXASHCDD4PQFKTMKQN4YOP5ZH366ABN4/", "https://access.redhat.com/errata/RHSA-2019:1260", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JMWSKTNOHSUOT3L25QFJAVCFYZX46FYK/", "https://lists.debian.org/debian-lts-announce/2019/06/msg00023.html", "https://lists.debian.org/debian-lts-announce/2019/06/msg00022.html", "https://lists.debian.org/debian-lts-announce/2019/06/msg00026.html", "https://access.redhat.com/errata/RHSA-2019:2030", "https://usn.ubuntu.com/4127-2/", "https://usn.ubuntu.com/4127-1/", "http://lists.opensuse.org/opensuse-security-announce/2019-10/msg00062.html", "http://lists.opensuse.org/opensuse-security-announce/2019-10/msg00063.html", "https://access.redhat.com/errata/RHSA-2019:3335", "https://access.redhat.com/errata/RHSA-2019:3520", "https://access.redhat.com/errata/RHSA-2019:3725", "http://lists.opensuse.org/opensuse-security-announce/2020-01/msg00040.html", "https://security.gentoo.org/glsa/202003-26", "https://lists.debian.org/debian-lts-announce/2020/07/msg00011.html", "https://lists.debian.org/debian-lts-announce/2020/08/msg00034.html", "http://www.openwall.com/lists/oss-security/2021/02/04/2"]}
{"id": "CVE-2019-9948", "package": "pkg:pypi/python@2.7.12", "purl": "pkg:pypi/python@2.7.12", "package_type": "python", "package_usage": "N/A", "version": "2.7.12", "fix_version": null, "severity": "CRITICAL", "cvss_score": "9.1", "short_description": "urllib in Python 2.x through 2.7.16 supports the local_file: scheme, which makes it easier for remote attackers to bypass protection mechanisms that blacklist file: URIs, as demonstrated by triggering a urllib.urlopen('local_file:///etc/passwd') call.", "related_urls": ["https://github.com/python/cpython/pull/11842", "https://bugs.python.org/issue35907", "http://www.securityfocus.com/bid/107549", "https://security.netapp.com/advisory/ntap-20190404-0004/", "http://lists.opensuse.org/opensuse-security-announce/2019-04/msg00092.html", "http://lists.opensuse.org/opensuse-security-announce/2019-06/msg00050.html", "https://lists.debian.org/debian-lts-announce/2019/06/msg00022.html", "https://access.redhat.com/errata/RHSA-2019:1700", "https://lists.debian.org/debian-lts-announce/2019/07/msg00011.html", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KRYFIMISZ47NTAU3XWZUOFB7CYL62KES/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HQEQLXLOCR3SNM3AA5RRYJFQ5AZBYJ4L/", "https://access.redhat.com/errata/RHSA-2019:2030", "https://usn.ubuntu.com/4127-2/", "https://usn.ubuntu.com/4127-1/", "https://seclists.org/bugtraq/2019/Oct/29", "http://packetstormsecurity.com/files/154927/Slackware-Security-Advisory-python-Updates.html", "https://access.redhat.com/errata/RHSA-2019:3335", "https://access.redhat.com/errata/RHSA-2019:3520", "https://security.gentoo.org/glsa/202003-26", "https://lists.debian.org/debian-lts-announce/2020/07/msg00011.html", "https://lists.apache.org/thread.html/r1b103833cb5bc8466e24ff0ecc5e75b45a705334ab6a444e64e840a0@%3Cissues.bookkeeper.apache.org%3E", "https://lists.debian.org/debian-lts-announce/2020/08/msg00034.html"]}
{"id": "CVE-2018-1000030", "package": "pkg:pypi/python@2.7.12", "purl": "pkg:pypi/python@2.7.12", "package_type": "python", "package_usage": "N/A", "version": "2.7.12", "fix_version": null, "severity": "LOW", "cvss_score": "3.6", "short_description": "Python 2.7.14 is vulnerable to a Heap-Buffer-Overflow as well as a Heap-Use-After-Free. Python versions prior to 2.7.14 may also be vulnerable and it appears that Python 2.7.17 and prior may also be vulnerable however this has not been confirmed. The vulnerability lies when multiply threads are handling large amounts of data. In both cases there is essentially a race condition that occurs. For the Heap-Buffer-Overflow, Thread 2 is creating the size for a buffer, but Thread1 is already writing to the buffer without knowing how much to write. So when a large amount of data is being processed, it is very easy to cause memory corruption using a Heap-Buffer-Overflow. As for the Use-After-Free, Thread3->Malloc->Thread1->Free's->Thread2-Re-uses-Free'd Memory. The PSRT has stated that this is not a security vulnerability due to the fact that the attacker must be able to run code, however in some situations, such as function as a service, this vulnerability can potentially be used by an attacker to violate a trust boundary, as such the DWF feels this issue deserves a CVE.", "related_urls": ["https://www.dropbox.com/sh/sj3ee7xv55j36k7/AADwP-YfOYikBMuy32e0uvPFa?dl=0", "https://drive.google.com/file/d/1oyR9DAZjZK_SCn3mor6NRAYLJS6ueXaY/view", "https://bugs.python.org/issue31530", "https://security.gentoo.org/glsa/201811-02", "https://usn.ubuntu.com/3817-1/", "https://usn.ubuntu.com/3817-2/", "https://www.oracle.com/security-alerts/cpujan2020.html"]}
{"id": "CVE-2018-1060", "package": "pkg:pypi/python@2.7.12", "purl": "pkg:pypi/python@2.7.12", "package_type": "python", "package_usage": "N/A", "version": "2.7.12", "fix_version": "2.7.15", "severity": "HIGH", "cvss_score": "7.5", "short_description": "python before versions 2.7.15, 3.4.9, 3.5.6rc1, 3.6.5rc1 and 3.7.0 is vulnerable to catastrophic backtracking in pop3lib's apop() method. An attacker could use this flaw to cause denial of service.", "related_urls": ["https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-1060", "https://bugs.python.org/issue32981", "https://docs.python.org/3.6/whatsnew/changelog.html#python-3-6-5-release-candidate-1", "https://docs.python.org/3.5/whatsnew/changelog.html#python-3-5-6-release-candidate-1", "https://lists.debian.org/debian-lts-announce/2018/09/msg00031.html", "https://lists.debian.org/debian-lts-announce/2018/09/msg00030.html", "https://www.debian.org/security/2018/dsa-4306", "https://www.debian.org/security/2018/dsa-4307", "https://access.redhat.com/errata/RHSA-2018:3041", "https://access.redhat.com/errata/RHSA-2018:3505", "https://usn.ubuntu.com/3817-1/", "http://www.securitytracker.com/id/1042001", "https://usn.ubuntu.com/3817-2/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JSKPGPZQNTAULHW4UH63KGOOUIDE4RRB/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/AEZ5IQT7OF7Q2NCGIVABOWYGKO7YU3NJ/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/46PVWY5LFP4BRPG3BVQ5QEEFYBVEXHCK/", "https://access.redhat.com/errata/RHBA-2019:0327", "https://access.redhat.com/errata/RHSA-2019:1260", "https://support.hpe.com/hpsc/doc/public/display?docLocale=en_US&docId=emr_na-hpesbst03951en_us", "https://access.redhat.com/errata/RHSA-2019:3725", "https://www.oracle.com/security-alerts/cpujan2020.html", "http://lists.opensuse.org/opensuse-security-announce/2020-01/msg00040.html"]}
{"id": "CVE-2018-1061", "package": "pkg:pypi/python@2.7.12", "purl": "pkg:pypi/python@2.7.12", "package_type": "python", "package_usage": "N/A", "version": "2.7.12", "fix_version": "2.7.15", "severity": "HIGH", "cvss_score": "7.5", "short_description": "python before versions 2.7.15, 3.4.9, 3.5.6rc1, 3.6.5rc1 and 3.7.0 is vulnerable to catastrophic backtracking in the difflib.IS_LINE_JUNK method.  An attacker could use this flaw to cause denial of service.", "related_urls": ["https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-1061", "https://bugs.python.org/issue32981", "https://docs.python.org/3.6/whatsnew/changelog.html#python-3-6-5-release-candidate-1", "https://docs.python.org/3.5/whatsnew/changelog.html#python-3-5-6-release-candidate-1", "https://lists.debian.org/debian-lts-announce/2018/09/msg00031.html", "https://lists.debian.org/debian-lts-announce/2018/09/msg00030.html", "https://www.debian.org/security/2018/dsa-4306", "https://www.debian.org/security/2018/dsa-4307", "https://access.redhat.com/errata/RHSA-2018:3041", "https://access.redhat.com/errata/RHSA-2018:3505", "https://usn.ubuntu.com/3817-1/", "http://www.securitytracker.com/id/1042001", "https://usn.ubuntu.com/3817-2/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JSKPGPZQNTAULHW4UH63KGOOUIDE4RRB/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/AEZ5IQT7OF7Q2NCGIVABOWYGKO7YU3NJ/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/46PVWY5LFP4BRPG3BVQ5QEEFYBVEXHCK/", "https://access.redhat.com/errata/RHBA-2019:0327", "https://access.redhat.com/errata/RHSA-2019:1260", "https://support.hpe.com/hpsc/doc/public/display?docLocale=en_US&docId=emr_na-hpesbst03951en_us", "https://access.redhat.com/errata/RHSA-2019:3725", "http://lists.opensuse.org/opensuse-security-announce/2020-01/msg00040.html"]}
{"id": "CVE-2018-14647", "package": "pkg:pypi/python@2.7.12", "purl": "pkg:pypi/python@2.7.12", "package_type": "python", "package_usage": "N/A", "version": "2.7.12", "fix_version": null, "severity": "HIGH", "cvss_score": "7.5", "short_description": "Python's elementtree C accelerator failed to initialise Expat's hash salt during initialization. This could make it easy to conduct denial of service attacks against Expat by constructing an XML document that would cause pathological hash collisions in Expat's internal data structures, consuming large amounts CPU and RAM. The vulnerability exists in Python versions 3.7.0, 3.6.0 through 3.6.6, 3.5.0 through 3.5.6, 3.4.0 through 3.4.9, 2.7.0 through 2.7.15.", "related_urls": ["https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-14647", "https://bugs.python.org/issue34623", "http://www.securityfocus.com/bid/105396", "https://www.debian.org/security/2018/dsa-4306", "https://www.debian.org/security/2018/dsa-4307", "http://www.securitytracker.com/id/1041740", "https://usn.ubuntu.com/3817-1/", "https://usn.ubuntu.com/3817-2/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/RBJCB2HWOJLP3L7CUQHJHNBHLSVOXJE5/", "https://access.redhat.com/errata/RHSA-2019:1260", "https://lists.debian.org/debian-lts-announce/2019/06/msg00023.html", "https://lists.debian.org/debian-lts-announce/2019/06/msg00022.html", "https://access.redhat.com/errata/RHSA-2019:2030", "https://access.redhat.com/errata/RHSA-2019:3725", "http://lists.opensuse.org/opensuse-security-announce/2020-01/msg00040.html", "https://lists.apache.org/thread.html/r1b103833cb5bc8466e24ff0ecc5e75b45a705334ab6a444e64e840a0@%3Cissues.bookkeeper.apache.org%3E"]}
{"id": "CVE-2018-20852", "package": "pkg:pypi/python@2.7.12", "purl": "pkg:pypi/python@2.7.12", "package_type": "python", "package_usage": "N/A", "version": "2.7.12", "fix_version": null, "severity": "MEDIUM", "cvss_score": "5.3", "short_description": "http.cookiejar.DefaultPolicy.domain_return_ok in Lib/http/cookiejar.py in Python before 3.7.3 does not correctly validate the domain: it can be tricked into sending existing cookies to the wrong server. An attacker may abuse this flaw by using a server with a hostname that has another valid hostname as a suffix (e.g., pythonicexample.com to steal cookies for example.com). When a program uses http.cookiejar.DefaultPolicy and tries to do an HTTP connection to an attacker-controlled server, existing cookies can be leaked to the attacker. This affects 2.x through 2.7.16, 3.x before 3.4.10, 3.5.x before 3.5.7, 3.6.x before 3.6.9, and 3.7.x before 3.7.3.", "related_urls": ["https://bugs.python.org/issue35121", "https://python-security.readthedocs.io/vuln/cookie-domain-check.html", "https://lists.debian.org/debian-lts-announce/2019/08/msg00022.html", "http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00071.html", "http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00074.html", "https://lists.debian.org/debian-lts-announce/2019/08/msg00040.html", "https://usn.ubuntu.com/4127-2/", "https://usn.ubuntu.com/4127-1/", "https://access.redhat.com/errata/RHSA-2019:3725", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/K7HNVIFMETMFWWWUNTB72KYJYXCZOS5V/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZBTGPBUABGXZ7WH7677OEM3NSP6ZEA76/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/COATURTCY7G67AYI6UDV5B2JZTBCKIDX/", "https://access.redhat.com/errata/RHSA-2019:3948", "http://lists.opensuse.org/opensuse-security-announce/2020-01/msg00040.html", "https://security.gentoo.org/glsa/202003-26", "https://www.oracle.com/security-alerts/cpuapr2020.html", "https://lists.debian.org/debian-lts-announce/2020/07/msg00011.html", "https://lists.debian.org/debian-lts-announce/2020/08/msg00034.html"]}
{"id": "CVE-2017-1000158", "package": "pkg:pypi/python@2.7.12", "purl": "pkg:pypi/python@2.7.12", "package_type": "python", "package_usage": "N/A", "version": "2.7.12", "fix_version": null, "severity": "CRITICAL", "cvss_score": "9.8", "short_description": "CPython (aka Python) up to 2.7.13 is vulnerable to an integer overflow in the PyString_DecodeEscape function in stringobject.c, resulting in heap-based buffer overflow (and possible arbitrary code execution)", "related_urls": ["https://bugs.python.org/issue30657", "http://www.securitytracker.com/id/1039890", "https://lists.debian.org/debian-lts-announce/2017/11/msg00036.html", "https://lists.debian.org/debian-lts-announce/2017/11/msg00035.html", "https://lists.debian.org/debian-lts-announce/2018/09/msg00031.html", "https://lists.debian.org/debian-lts-announce/2018/09/msg00030.html", "https://www.debian.org/security/2018/dsa-4307", "https://security.gentoo.org/glsa/201805-02"]}
{"id": "CVE-2017-18589", "package": "pkg:npm/cookie@0.5.0", "purl": "pkg:npm/cookie@0.5.0", "package_type": "cookie_project", "package_usage": "N/A", "version": "0.5.0", "fix_version": "0.7.6", "severity": "HIGH", "cvss_score": "7.5", "short_description": "An issue was discovered in the cookie crate before 0.7.6 for Rust. Large integers in the Max-Age of a cookie cause a panic.", "related_urls": ["https://rustsec.org/advisories/RUSTSEC-2017-0005.html"]}
